# ~/.bashrc template
# Copy to ~/.bashrc and customize

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

# Auto-switch to fish shell
if [ -x "$(command -v fish)" ]; then
    exec fish
fi

# Local bin
. "$HOME/.local/bin/env"

# npm global path
export PATH="$HOME/.local/bin:$HOME/.npm-global/bin:$PATH"
